-- Drop existing tables to replace them
drop table if exists public.curriculum_assignments cascade;
drop table if exists public.personalized_curricula cascade;
drop table if exists public.practice_assignments cascade;

-- Expand the practice onboarding with curriculum tables
create table if not exists public.practice_assignments (
  id uuid default gen_random_uuid() primary key,
  title text not null,
  type text not null check (type in ('conversation', 'pronunciation')),
  level text not null check (level in ('BEGINNER', 'INTERMEDIATE', 'ADVANCED')),
  description text,
  content jsonb not null, -- scenario data or pronunciation transcript
  estimated_duration integer default 10, -- in minutes
  ielts_focus_areas text[] default array['speaking'], 
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create table if not exists public.personalized_curricula (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  name text not null,
  description text,
  target_score text not null,
  current_level text not null,
  frequency_days integer not null, -- 15, 30, 60, 90
  total_weeks integer not null, -- max 8
  total_assignments integer default 0,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create table if not exists public.curriculum_assignments (
  id uuid default gen_random_uuid() primary key,
  curriculum_id uuid references public.personalized_curricula(id) on delete cascade not null,
  assignment_id uuid references public.practice_assignments(id) on delete cascade not null,
  week_number integer not null check (week_number between 1 and 8),
  sequence_order integer not null,
  is_completed boolean default false,
  completed_at timestamp with time zone,
  created_at timestamp with time zone default now()
);

-- Insert conversation assignments (from existing scenarios)
insert into public.practice_assignments (title, type, level, description, content) values
-- BEGINNER conversations
-- Beginner Conversation Scenarios with Complete Scripts
-- BEGINNER IELTS Topics (20 scenarios)

('Family and Relatives', 'conversation', 'BEGINNER', 'Discuss family members and relationships - IELTS Part 1 topic',
 '{"id": "family-relatives", "name": "Family and Relatives", "level": "BEGINNER", "description": "Discuss family members and relationships - IELTS Part 1 topic", "greeting": "Let''s talk about your family. Can you tell me about your family members?", "instructions": "You are an IELTS examiner asking about family. Keep questions simple and encourage detailed responses about family relationships.", "turns": 4, "icon": "👨‍👩‍👧‍👦", "conversationScript": [{"turn": 1, "agent": "Let''s talk about your family. Can you tell me about your family members?", "suggestedResponse": "I have a small family. There are four people in my family - my parents, my younger brother, and me. We live together in the same house and we are very close to each other."}, {"turn": 2, "agent": "That sounds lovely. How much time do you spend with your family?", "suggestedResponse": "I spend quite a lot of time with my family, especially on weekends. We usually have dinner together every evening and talk about our day. During holidays, we like to go on trips together or visit our relatives."}, {"turn": 3, "agent": "What activities do you enjoy doing together as a family?", "suggestedResponse": "We enjoy many activities together like watching movies, playing board games, and cooking. My mother teaches me traditional recipes from our culture. Sometimes we go hiking or have picnics in the park near our house."}, {"turn": 4, "agent": "Do you think family relationships are important? Why?", "suggestedResponse": "Yes, I believe family relationships are extremely important because they provide love, support, and guidance throughout our lives. Family members help us during difficult times and celebrate our achievements with us. They also teach us important values and traditions."}]}'),

('Hometown Description', 'conversation', 'BEGINNER', 'Describe your hometown and local area - IELTS Part 1 topic',
 '{"id": "hometown-description", "name": "Hometown Description", "level": "BEGINNER", "description": "Describe your hometown and local area - IELTS Part 1 topic", "greeting": "I''d like to know about your hometown. Where are you from?", "instructions": "You are an IELTS examiner asking about the candidate''s hometown. Encourage descriptive answers about places and local features.", "turns": 4, "icon": "🏙️", "conversationScript": [{"turn": 1, "agent": "I''d like to know about your hometown. Where are you from?", "suggestedResponse": "I''m from a medium-sized city called Springfield in the northern part of my country. It has about 200,000 people and is known for its beautiful parks and historic buildings. The city is located near a large river which makes it very scenic."}, {"turn": 2, "agent": "What do you like most about your hometown?", "suggestedResponse": "What I like most is the friendly community and the peaceful atmosphere. The people are very welcoming and always willing to help each other. There are also many green spaces and the air quality is much better than in larger cities."}, {"turn": 3, "agent": "How has your hometown changed since you were a child?", "suggestedResponse": "My hometown has changed quite a bit over the years. Many new shopping centers and restaurants have been built, which gives us more entertainment options. However, there''s also more traffic now, and some of the old traditional buildings have been replaced with modern ones."}, {"turn": 4, "agent": "Would you like to live there in the future?", "suggestedResponse": "I think I would like to return there eventually, especially when I start a family. It''s a great place to raise children because it''s safe and has good schools. However, right now I want to experience living in different places to broaden my horizons."}]}'),

('Daily Routine', 'conversation', 'BEGINNER', 'Talk about daily activities and schedules - IELTS Part 1 topic',
 '{"id": "daily-routine", "name": "Daily Routine", "level": "BEGINNER", "description": "Talk about daily activities and schedules - IELTS Part 1 topic", "greeting": "Let''s discuss your daily routine. What time do you usually wake up?", "instructions": "You are an IELTS examiner asking about daily routines. Focus on time management and regular activities.", "turns": 4, "icon": "⏰", "conversationScript": [{"turn": 1, "agent": "Let''s discuss your daily routine. What time do you usually wake up?", "suggestedResponse": "I usually wake up at 6:30 in the morning on weekdays because I need to get ready for work. I like to have enough time for a proper breakfast and to prepare for the day ahead. On weekends, I allow myself to sleep in until around 8 or 9 o''clock."}, {"turn": 2, "agent": "What do you do in the evening after work or study?", "suggestedResponse": "In the evening, I usually return home around 6 PM and have dinner with my family. After that, I like to relax by reading books, watching TV shows, or chatting with friends online. Before bed, I often review my plans for the next day and do some light exercise."}, {"turn": 3, "agent": "Do you prefer to have a fixed routine or do you like variety?", "suggestedResponse": "I prefer to have a basic routine because it helps me stay organized and productive. However, I also like some variety, especially on weekends when I can try new activities or visit different places. Having structure during the week makes the spontaneous weekend activities more enjoyable."}, {"turn": 4, "agent": "How do you manage your time effectively?", "suggestedResponse": "I manage my time by making to-do lists and prioritizing important tasks first. I also try to avoid distractions like social media during work hours. Planning my day the night before really helps me stay focused and accomplish my goals more efficiently."}]}'),

('Food and Cooking', 'conversation', 'BEGINNER', 'Discuss food preferences and cooking habits - IELTS Part 1 topic',
 '{"id": "food-cooking", "name": "Food and Cooking", "level": "BEGINNER", "description": "Discuss food preferences and cooking habits - IELTS Part 1 topic", "greeting": "Let''s talk about food. What kind of food do you like to eat?", "instructions": "You are an IELTS examiner asking about food and cooking. Encourage discussion about preferences, cooking skills, and cultural foods.", "turns": 4, "icon": "🍳", "conversationScript": [{"turn": 1, "agent": "Let''s talk about food. What kind of food do you like to eat?", "suggestedResponse": "I enjoy eating a variety of foods, but I particularly love traditional dishes from my country like pasta and pizza. I also like trying international cuisines such as Asian stir-fries and Mexican tacos. Fresh vegetables and fruits are important parts of my diet because they keep me healthy."}, {"turn": 2, "agent": "Do you know how to cook? What dishes can you prepare?", "suggestedResponse": "Yes, I can cook basic dishes like fried rice, scrambled eggs, and simple pasta. My mother taught me how to make our family''s traditional soup recipe, which is my specialty. I''m still learning more advanced cooking techniques by watching online tutorials and practicing on weekends."}, {"turn": 3, "agent": "Do you prefer eating at home or in restaurants?", "suggestedResponse": "I prefer eating at home most of the time because it''s more economical and I can control the ingredients and portions. Home-cooked meals are usually healthier and taste better to me. However, I do enjoy going to restaurants occasionally for special occasions or to try new cuisines."}, {"turn": 4, "agent": "How important is food in your culture?", "suggestedResponse": "Food is extremely important in my culture because it brings families and communities together. We have many traditional festivals that center around special dishes and sharing meals. Cooking and eating together is a way to show love, maintain traditions, and strengthen relationships between generations."}]}'),

('Hobbies and Interests', 'conversation', 'BEGINNER', 'Share personal hobbies and leisure activities - IELTS Part 1 topic',
 '{"id": "hobbies-interests", "name": "Hobbies and Interests", "level": "BEGINNER", "description": "Share personal hobbies and leisure activities - IELTS Part 1 topic", "greeting": "What do you like to do in your free time?", "instructions": "You are an IELTS examiner asking about hobbies and interests. Encourage detailed explanations about activities and their benefits.", "turns": 4, "icon": "🎨", "conversationScript": [{"turn": 1, "agent": "What do you like to do in your free time?", "suggestedResponse": "In my free time, I enjoy reading novels and short stories because they help me relax and improve my vocabulary. I also like playing basketball with my friends on weekends, which keeps me physically active. Recently, I''ve started learning to play the guitar, which is challenging but very rewarding."}, {"turn": 2, "agent": "How long have you been interested in these activities?", "suggestedResponse": "I''ve been reading since I was a child, probably for about fifteen years now. Basketball became my passion during high school, so that''s been about six years. The guitar is my newest hobby - I just started three months ago when my friend offered to teach me."}, {"turn": 3, "agent": "Do you prefer indoor or outdoor activities?", "suggestedResponse": "I enjoy both indoor and outdoor activities because they offer different benefits. Indoor activities like reading and playing guitar are perfect for relaxing and developing skills quietly. Outdoor activities like basketball and hiking give me fresh air, exercise, and the chance to socialize with others."}, {"turn": 4, "agent": "Would you like to try any new hobbies in the future?", "suggestedResponse": "Yes, I''d love to try photography because I think it would help me see the world from different perspectives. I''m also interested in learning a new language, possibly Spanish or French. Cooking is another hobby I want to develop further to create more delicious and healthy meals."}]}'),

('Weather and Seasons', 'conversation', 'BEGINNER', 'Discuss weather patterns and seasonal preferences - IELTS Part 1 topic',
 '{"id": "weather-seasons", "name": "Weather and Seasons", "level": "BEGINNER", "description": "Discuss weather patterns and seasonal preferences - IELTS Part 1 topic", "greeting": "Let''s talk about weather. What''s the weather like in your country?", "instructions": "You are an IELTS examiner asking about weather and seasons. Focus on climate, preferences, and seasonal activities.", "turns": 4, "icon": "🌦️", "conversationScript": [{"turn": 1, "agent": "Let''s talk about weather. What''s the weather like in your country?", "suggestedResponse": "My country has four distinct seasons with quite varied weather throughout the year. Summers are usually hot and humid with temperatures reaching 35 degrees Celsius. Winters can be quite cold with snow and temperatures dropping below freezing, while spring and autumn are mild and pleasant."}, {"turn": 2, "agent": "Which season do you like best and why?", "suggestedResponse": "I love autumn the most because the weather is comfortable - not too hot and not too cold. The leaves change to beautiful colors like red, orange, and yellow, making everything look spectacular. It''s also the perfect time for outdoor activities like hiking and having picnics without sweating or freezing."}, {"turn": 3, "agent": "How does weather affect your daily activities?", "suggestedResponse": "Weather significantly affects what I do each day. On rainy days, I prefer staying indoors reading or watching movies instead of going out. During hot summer days, I schedule outdoor activities early in the morning or late evening. In winter, I need to dress warmly and plan extra time for commuting due to snow."}, {"turn": 4, "agent": "Do you think climate change is affecting your area?", "suggestedResponse": "Yes, I''ve noticed that summers are becoming hotter and more humid than they used to be. We also experience more extreme weather events like heavy rainstorms and unexpected temperature changes. The timing of seasons seems to be shifting, with spring arriving earlier and winter lasting longer than in the past."}]}'),

('Transportation', 'conversation', 'BEGINNER', 'Talk about travel methods and commuting - IELTS Part 1 topic',
 '{"id": "transportation", "name": "Transportation", "level": "BEGINNER", "description": "Talk about travel methods and commuting - IELTS Part 1 topic", "greeting": "How do you usually get around your city?", "instructions": "You are an IELTS examiner asking about transportation. Discuss different modes of transport and their advantages.", "turns": 4, "icon": "🚊", "conversationScript": [{"turn": 1, "agent": "How do you usually get around your city?", "suggestedResponse": "I mainly use public transportation like buses and trains because they''re convenient and environmentally friendly. For short distances, I prefer walking or cycling because it''s good exercise and I can enjoy the fresh air. Occasionally, I take a taxi when I''m in a hurry or carrying heavy items."}, {"turn": 2, "agent": "What do you think about the public transport in your area?", "suggestedResponse": "The public transport system in my area is generally reliable and covers most parts of the city. The buses run frequently during peak hours, which is convenient for commuters. However, during rush hour, they can become quite crowded, and sometimes there are delays due to traffic congestion."}, {"turn": 3, "agent": "Do you have a driver''s license? Do you drive?", "suggestedResponse": "Yes, I have a driver''s license, but I don''t drive very often because parking is expensive and difficult to find in the city center. I mainly drive when I need to visit places that are not well-connected by public transport. I also drive when I go on weekend trips outside the city with my family."}, {"turn": 4, "agent": "How do you think transportation will change in the future?", "suggestedResponse": "I think transportation will become much more environmentally friendly with more electric buses, trains, and cars. Self-driving vehicles might become common, which could reduce traffic accidents and make commuting more efficient. We might also see more bike-sharing programs and better infrastructure for cyclists and pedestrians."}]}'),

('Technology and Internet', 'conversation', 'BEGINNER', 'Discuss technology use and digital habits - IELTS Part 1 topic',
 '{"id": "technology-internet", "name": "Technology and Internet", "level": "BEGINNER", "description": "Discuss technology use and digital habits - IELTS Part 1 topic", "greeting": "How often do you use the internet?", "instructions": "You are an IELTS examiner asking about technology and internet usage. Focus on daily use, benefits, and concerns.", "turns": 4, "icon": "💻", "conversationScript": [{"turn": 1, "agent": "How often do you use the internet?", "suggestedResponse": "I use the internet every day for several hours, mainly for work, education, and entertainment. I check my emails in the morning, use it for research during work hours, and browse social media or watch videos in the evening. It has become an essential part of my daily routine."}, {"turn": 2, "agent": "What do you mainly use your smartphone for?", "suggestedResponse": "I use my smartphone primarily for communication through calls, texts, and messaging apps to stay in touch with family and friends. I also use it for navigation when traveling, taking photos, listening to music, and checking the weather. It''s also handy for online banking and shopping when I''m away from my computer."}, {"turn": 3, "agent": "How has technology changed your life?", "suggestedResponse": "Technology has made my life much more convenient and efficient. I can access information instantly, work remotely, and connect with people around the world easily. Online learning platforms have helped me develop new skills, and digital payment systems have made transactions faster and safer."}, {"turn": 4, "agent": "Do you think people spend too much time on their devices?", "suggestedResponse": "Yes, I think many people, including myself sometimes, spend too much time on their devices. This can lead to reduced face-to-face social interaction and physical activity. However, if used wisely, technology can be very beneficial for learning, working, and maintaining relationships, so it''s about finding the right balance."}]}'),

('Work and Studies', 'conversation', 'BEGINNER', 'Discuss career, education, and future plans - IELTS Part 1 topic',
 '{"id": "work-studies", "name": "Work and Studies", "level": "BEGINNER", "description": "Discuss career, education, and future plans - IELTS Part 1 topic", "greeting": "Tell me about your work or studies.", "instructions": "You are an IELTS examiner asking about work or studies. Encourage discussion about current activities and future goals.", "turns": 4, "icon": "📚", "conversationScript": [{"turn": 1, "agent": "Tell me about your work or studies.", "suggestedResponse": "I''m currently a university student majoring in computer science. I''m in my third year and really enjoying the programming and software development courses. I chose this field because I''m passionate about technology and believe it offers excellent career opportunities in today''s digital world."}, {"turn": 2, "agent": "What do you find most challenging about your studies?", "suggestedResponse": "The most challenging aspect is keeping up with the rapidly changing technology and learning multiple programming languages simultaneously. Some theoretical concepts in algorithms and data structures require a lot of practice to fully understand. Time management is also difficult when balancing coursework, projects, and part-time work."}, {"turn": 3, "agent": "What are your plans after you finish your studies?", "suggestedResponse": "After graduation, I plan to work as a software developer for a technology company where I can apply my programming skills and continue learning. I''m particularly interested in mobile app development and artificial intelligence. Eventually, I might pursue a master''s degree to specialize further in machine learning."}, {"turn": 4, "agent": "Do you think your field of study is important for society?", "suggestedResponse": "Absolutely, computer science is crucial for modern society because technology affects almost every aspect of our lives. From healthcare systems to education platforms, software solutions help solve real-world problems and improve people''s quality of life. The field also drives innovation and economic growth in many industries."}]}'),

('Shopping and Money', 'conversation', 'BEGINNER', 'Talk about shopping habits and financial management - IELTS Part 1 topic',
 '{"id": "shopping-money", "name": "Shopping and Money", "level": "BEGINNER", "description": "Talk about shopping habits and financial management - IELTS Part 1 topic", "greeting": "Do you enjoy shopping? What do you usually buy?", "instructions": "You are an IELTS examiner asking about shopping and money management. Discuss spending habits and preferences.", "turns": 4, "icon": "🛒", "conversationScript": [{"turn": 1, "agent": "Do you enjoy shopping? What do you usually buy?", "suggestedResponse": "I moderately enjoy shopping, especially for books, clothes, and electronic gadgets. I usually buy necessary items like groceries, clothing, and household supplies rather than luxury items. I prefer shopping for things that are practical and will be used regularly rather than impulse purchases."}, {"turn": 2, "agent": "Do you prefer shopping online or in physical stores?", "suggestedResponse": "I prefer online shopping for most items because it''s more convenient and often offers better prices and variety. I can compare products easily and read customer reviews before making decisions. However, for clothes and shoes, I still prefer physical stores because I need to try them on to ensure proper fit."}, {"turn": 3, "agent": "How do you decide what to buy?", "suggestedResponse": "I usually make a list of things I need before shopping and stick to it to avoid unnecessary purchases. I compare prices from different sellers and read product reviews to ensure good quality. I also consider whether the item is really necessary and if I can afford it without affecting my budget."}, {"turn": 4, "agent": "Do you think it''s important to save money?", "suggestedResponse": "Yes, saving money is extremely important for financial security and future planning. It helps prepare for emergencies, unexpected expenses, and long-term goals like buying a house or retirement. I try to save a portion of my income each month and avoid spending on things I don''t really need."}]}'),

('Friends and Relationships', 'conversation', 'BEGINNER', 'Discuss friendships and social connections - IELTS Part 1 topic',
 '{"id": "friends-relationships", "name": "Friends and Relationships", "level": "BEGINNER", "description": "Discuss friendships and social connections - IELTS Part 1 topic", "greeting": "Tell me about your friends. How did you meet them?", "instructions": "You are an IELTS examiner asking about friendships and social relationships. Focus on how friendships form and their importance.", "turns": 4, "icon": "👥", "conversationScript": [{"turn": 1, "agent": "Tell me about your friends. How did you meet them?", "suggestedResponse": "I have several close friends that I met in different situations. My best friend and I have known each other since elementary school and we grew up in the same neighborhood. I also have good friends from university who share similar interests and study goals with me."}, {"turn": 2, "agent": "What do you like to do with your friends?", "suggestedResponse": "We enjoy doing various activities together like going to movies, trying new restaurants, and playing sports like basketball or badminton. Sometimes we just hang out at someone''s house, play video games, or have deep conversations about life. During holidays, we often plan short trips to nearby cities or natural areas."}, {"turn": 3, "agent": "Do you prefer to have many friends or just a few close ones?", "suggestedResponse": "I prefer to have a few close friends rather than many casual acquaintances. Deep, meaningful friendships require time and effort to maintain, so I focus on building strong relationships with people who truly understand and support me. Quality is more important to me than quantity when it comes to friendships."}, {"turn": 4, "agent": "How important are friends in your life?", "suggestedResponse": "Friends are extremely important in my life because they provide emotional support, companionship, and different perspectives on various situations. They make life more enjoyable and help me through difficult times by offering advice and encouragement. Good friends also help me grow as a person by challenging my thoughts and introducing me to new experiences."}]}'),

('Health and Exercise', 'conversation', 'BEGINNER', 'Talk about fitness routines and healthy lifestyle - IELTS Part 1 topic',
 '{"id": "health-exercise", "name": "Health and Exercise", "level": "BEGINNER", "description": "Talk about fitness routines and healthy lifestyle - IELTS Part 1 topic", "greeting": "Do you do any sports or exercise regularly?", "instructions": "You are an IELTS examiner asking about health and exercise habits. Encourage discussion about physical activity and wellness.", "turns": 4, "icon": "🏃‍♂️", "conversationScript": [{"turn": 1, "agent": "Do you do any sports or exercise regularly?", "suggestedResponse": "Yes, I try to exercise regularly to maintain my health and fitness. I go jogging three times a week in the morning before work, which helps me feel energized for the day. I also play tennis on weekends with friends, which is both fun and great exercise."}, {"turn": 2, "agent": "What do you do to stay healthy?", "suggestedResponse": "Besides regular exercise, I try to eat a balanced diet with plenty of fruits, vegetables, and lean proteins while limiting processed foods. I make sure to get enough sleep, usually 7-8 hours per night, and drink plenty of water throughout the day. I also try to manage stress through meditation and spending time in nature."}, {"turn": 3, "agent": "Do you think people in your country are generally healthy?", "suggestedResponse": "I think health levels vary widely among people in my country. Many young people are becoming more health-conscious and joining gyms or participating in sports activities. However, busy modern lifestyles often lead to poor eating habits and lack of exercise, especially among working adults who spend long hours at desks."}, {"turn": 4, "agent": "How important is it to maintain good health?", "suggestedResponse": "Maintaining good health is extremely important because it affects every aspect of our lives including our energy levels, mood, and ability to enjoy activities. Good health allows us to be productive at work, maintain relationships, and pursue our goals. It also helps prevent serious diseases and reduces healthcare costs in the long term."}]}'),

('Music and Entertainment', 'conversation', 'BEGINNER', 'Discuss musical preferences and entertainment choices - IELTS Part 1 topic',
 '{"id": "music-entertainment", "name": "Music and Entertainment", "level": "BEGINNER", "description": "Discuss musical preferences and entertainment choices - IELTS Part 1 topic", "greeting": "What kind of music do you like to listen to?", "instructions": "You are an IELTS examiner asking about music and entertainment preferences. Focus on tastes, habits, and cultural aspects.", "turns": 4, "icon": "🎵", "conversationScript": [{"turn": 1, "agent": "What kind of music do you like to listen to?", "suggestedResponse": "I enjoy listening to various types of music depending on my mood and the situation. I particularly love pop and rock music because they have catchy melodies and energetic beats that motivate me. I also appreciate classical music when I want to relax or concentrate on studying."}, {"turn": 2, "agent": "How often do you listen to music?", "suggestedResponse": "I listen to music almost every day, especially during my commute to work or university. I often have music playing in the background while doing household chores or exercising because it makes these activities more enjoyable. I also attend live concerts occasionally when my favorite artists perform in my city."}, {"turn": 3, "agent": "Do you play any musical instruments?", "suggestedResponse": "I learned to play the piano when I was younger and still play occasionally for relaxation and personal enjoyment. Although I''m not an expert, I can play some of my favorite songs and simple classical pieces. I''ve been thinking about taking guitar lessons because I think it would be fun to learn a different type of instrument."}, {"turn": 4, "agent": "How important is music in your culture?", "suggestedResponse": "Music plays a very important role in my culture, especially during festivals, celebrations, and religious ceremonies. Traditional folk songs help preserve our cultural heritage and tell stories about our history and values. Many families also bond through music by singing together or attending cultural performances that showcase our traditional instruments and dances."}]}'),

('Travel and Holidays', 'conversation', 'BEGINNER', 'Share travel experiences and vacation preferences - IELTS Part 1 topic',
 '{"id": "travel-holidays", "name": "Travel and Holidays", "level": "BEGINNER", "description": "Share travel experiences and vacation preferences - IELTS Part 1 topic", "greeting": "Do you like to travel? Where have you been?", "instructions": "You are an IELTS examiner asking about travel and holidays. Encourage sharing of experiences and future plans.", "turns": 4, "icon": "✈️", "conversationScript": [{"turn": 1, "agent": "Do you like to travel? Where have you been?", "suggestedResponse": "Yes, I love traveling because it allows me to experience different cultures, try new foods, and see beautiful places. I''ve visited several countries in Europe including Italy, France, and Germany, as well as some neighboring countries in my region. Each trip taught me something new and broadened my perspective on the world."}, {"turn": 2, "agent": "What kind of places do you prefer to visit?", "suggestedResponse": "I prefer visiting places that combine natural beauty with rich cultural heritage, such as cities with historic architecture surrounded by mountains or coastlines. I enjoy destinations where I can both relax and learn, like museums, ancient ruins, or traditional markets. I also love places where I can interact with local people and experience their daily life."}, {"turn": 3, "agent": "Do you prefer to travel alone or with others?", "suggestedResponse": "I usually prefer traveling with family or close friends because sharing experiences makes them more memorable and enjoyable. It''s also safer and more economical to split costs for accommodation and transportation. However, I think solo travel can be valuable too because it pushes you to be more independent and meet new people."}, {"turn": 4, "agent": "Where would you like to travel in the future?", "suggestedResponse": "I''d love to visit Japan because I''m fascinated by their unique culture, delicious cuisine, and beautiful temples and gardens. I''m also interested in exploring South America, particularly countries like Peru and Brazil, to see ancient ruins and experience their vibrant cultures. Australia is another destination on my list because of its diverse wildlife and stunning landscapes."}]}'),

('Books and Reading', 'conversation', 'BEGINNER', 'Discuss reading habits and literature preferences - IELTS Part 1 topic',
 '{"id": "books-reading", "name": "Books and Reading", "level": "BEGINNER", "description": "Discuss reading habits and literature preferences - IELTS Part 1 topic", "greeting": "Do you like reading? What kind of books do you read?", "instructions": "You are an IELTS examiner asking about reading habits and book preferences. Focus on genres, benefits, and reading culture.", "turns": 4, "icon": "📖", "conversationScript": [{"turn": 1, "agent": "Do you like reading? What kind of books do you read?", "suggestedResponse": "Yes, I''m passionate about reading and try to read at least one book every month. I particularly enjoy mystery and thriller novels because they keep me engaged and guessing until the end. I also read self-help books and biographies because they provide valuable life lessons and inspire me to improve myself."}, {"turn": 2, "agent": "When and where do you usually read?", "suggestedResponse": "I usually read before going to bed because it helps me relax and unwind after a busy day. I also read during my lunch breaks at work and while commuting on public transportation. My favorite reading spot is a comfortable chair by the window in my living room where I can enjoy natural light and a quiet atmosphere."}, {"turn": 3, "agent": "Do you prefer physical books or digital books?", "suggestedResponse": "I prefer physical books because I enjoy the tactile experience of turning pages and the smell of paper. Physical books also don''t strain my eyes as much as digital screens do during long reading sessions. However, I do use e-books when traveling because they''re more convenient and I can carry many books in one device."}, {"turn": 4, "agent": "Do you think reading is important? Why?", "suggestedResponse": "Yes, reading is extremely important because it improves vocabulary, critical thinking skills, and general knowledge about the world. It also enhances imagination and empathy by allowing us to experience different perspectives and situations. Reading keeps our minds active and provides entertainment while teaching us valuable lessons about life, history, and human nature."}]}'),

('Sports and Competition', 'conversation', 'BEGINNER', 'Talk about sports interests and competitive activities - IELTS Part 1 topic',
 '{"id": "sports-competition", "name": "Sports and Competition", "level": "BEGINNER", "description": "Talk about sports interests and competitive activities - IELTS Part 1 topic", "greeting": "Are you interested in sports? Do you play or watch any sports?", "instructions": "You are an IELTS examiner asking about sports and competition. Discuss participation, watching, and the role of sports in society.", "turns": 4, "icon": "⚽", "conversationScript": [{"turn": 1, "agent": "Are you interested in sports? Do you play or watch any sports?", "suggestedResponse": "Yes, I''m quite interested in sports both as a participant and spectator. I play basketball twice a week with friends from work, which keeps me physically fit and helps build teamwork skills. I also enjoy watching football matches on television, especially during major tournaments like the World Cup."}, {"turn": 2, "agent": "What sports are popular in your country?", "suggestedResponse": "Football is by far the most popular sport in my country, with millions of fans following local and international teams. Basketball and volleyball are also very popular, especially among young people and students. Traditional sports like martial arts and table tennis also have strong followings and are often taught in schools."}, {"turn": 3, "agent": "Do you think sports are important for children?", "suggestedResponse": "Absolutely, sports are crucial for children''s physical and mental development. They help build strong muscles and bones, improve coordination, and establish healthy lifestyle habits early in life. Sports also teach important life skills like teamwork, discipline, perseverance, and how to handle both victory and defeat gracefully."}, {"turn": 4, "agent": "How do you think sports bring people together?", "suggestedResponse": "Sports have an amazing ability to unite people regardless of their background, nationality, or social status. Major sporting events like the Olympics create a sense of global community and shared excitement. Local sports teams help build community pride and give people common topics to discuss and bond over with neighbors and colleagues."}]}'),

('Art and Creativity', 'conversation', 'BEGINNER', 'Discuss artistic interests and creative expression - IELTS Part 1 topic',
 '{"id": "art-creativity", "name": "Art and Creativity", "level": "BEGINNER", "description": "Discuss artistic interests and creative expression - IELTS Part 1 topic", "greeting": "Are you interested in art? Do you create any art yourself?", "instructions": "You are an IELTS examiner asking about art and creativity. Focus on appreciation, participation, and cultural significance.", "turns": 4, "icon": "🎨", "conversationScript": [{"turn": 1, "agent": "Are you interested in art? Do you create any art yourself?", "suggestedResponse": "Yes, I''m very interested in art and find it fascinating how artists can express emotions and ideas through visual media. I enjoy drawing and painting as a hobby, though I''m still learning and improving my techniques. I particularly like watercolor painting because of its fluid and unpredictable nature that creates beautiful, unexpected effects."}, {"turn": 2, "agent": "What kind of art do you like to look at?", "suggestedResponse": "I''m drawn to impressionist paintings because of their use of light and color to create mood and atmosphere. I also appreciate modern abstract art because it challenges viewers to interpret meaning in their own way. Photography is another art form I enjoy, especially nature photography that captures the beauty of landscapes and wildlife."}, {"turn": 3, "agent": "Do you visit art galleries or museums?", "suggestedResponse": "Yes, I try to visit art galleries and museums whenever I have the opportunity, especially when traveling to new cities. These visits inspire my own artistic work and help me learn about different cultures and historical periods. I find that seeing artwork in person provides a much richer experience than viewing reproductions in books or online."}, {"turn": 4, "agent": "Why do you think art is important in society?", "suggestedResponse": "Art is essential because it preserves cultural heritage and provides a way for people to express their deepest thoughts and emotions. It challenges us to see the world from different perspectives and encourages critical thinking and creativity. Art also beautifies our environment and provides therapeutic benefits, helping people cope with stress and find meaning in their lives."}]}'),

('Environment and Nature', 'conversation', 'BEGINNER', 'Talk about environmental concerns and nature appreciation - IELTS Part 1 topic',
 '{"id": "environment-nature", "name": "Environment and Nature", "level": "BEGINNER", "description": "Talk about environmental concerns and nature appreciation - IELTS Part 1 topic", "greeting": "Do you care about environmental issues? What do you do to protect the environment?", "instructions": "You are an IELTS examiner asking about environmental awareness and actions. Focus on personal responsibility and nature connection.", "turns": 4, "icon": "🌱", "conversationScript": [{"turn": 1, "agent": "Do you care about environmental issues? What do you do to protect the environment?", "suggestedResponse": "Yes, I''m very concerned about environmental issues because they affect our planet''s future and the quality of life for future generations. I try to reduce my environmental impact by recycling waste, using public transportation instead of driving, and conserving water and electricity at home. I also avoid single-use plastics whenever possible."}, {"turn": 2, "agent": "Do you enjoy spending time in nature?", "suggestedResponse": "Absolutely, I love spending time in nature because it helps me feel peaceful and connected to the natural world. I often go hiking in nearby forests or parks on weekends to enjoy fresh air and beautiful scenery. Being in nature also provides a break from technology and urban stress, which is very refreshing for both mind and body."}, {"turn": 3, "agent": "What environmental problems concern you most?", "suggestedResponse": "Climate change is my biggest concern because it causes rising temperatures, extreme weather events, and threatens many plant and animal species. Air pollution in cities is also worrying because it affects public health and quality of life. Plastic pollution in oceans is another serious issue that harms marine life and food chains."}, {"turn": 4, "agent": "How can individuals make a difference for the environment?", "suggestedResponse": "Individuals can make a significant difference through small daily actions that add up to large impacts when many people participate. We can reduce energy consumption, choose sustainable products, support environmentally responsible companies, and educate others about environmental issues. Voting for leaders who prioritize environmental protection and participating in community cleanup activities are also important ways to contribute."}]}'),

('Languages and Communication', 'conversation', 'BEGINNER', 'Discuss language learning and communication skills - IELTS Part 1 topic',
 '{"id": "languages-communication", "name": "Languages and Communication", "level": "BEGINNER", "description": "Discuss language learning and communication skills - IELTS Part 1 topic", "greeting": "How many languages can you speak? Which languages are you learning?", "instructions": "You are an IELTS examiner asking about language abilities and learning. Focus on motivation, challenges, and benefits of multilingualism.", "turns": 4, "icon": "🗣️", "conversationScript": [{"turn": 1, "agent": "How many languages can you speak? Which languages are you learning?", "suggestedResponse": "I can speak three languages fluently: my native language, English, and Spanish. I''m currently learning French because I''m planning to study abroad in France next year. I started learning English in elementary school and Spanish in high school, but French is my newest challenge that I began six months ago."}, {"turn": 2, "agent": "Why do you think learning languages is important?", "suggestedResponse": "Learning languages is crucial in today''s globalized world because it opens doors to better career opportunities and allows for deeper cultural understanding. Speaking multiple languages helps you communicate with people from different backgrounds and appreciate their perspectives. It also improves cognitive abilities like memory, problem-solving, and multitasking skills."}, {"turn": 3, "agent": "What''s the most difficult part of learning a new language?", "suggestedResponse": "The most challenging aspect for me is mastering pronunciation and developing natural-sounding speech patterns. Grammar rules can also be confusing, especially when they''re very different from my native language. Building vocabulary takes time and constant practice, and understanding cultural contexts and idiomatic expressions requires extensive exposure to the language."}, {"turn": 4, "agent": "How do you practice speaking in foreign languages?", "suggestedResponse": "I practice speaking by having conversations with native speakers through language exchange apps and joining local conversation groups in my city. I also watch movies and TV shows in the target language and try to repeat dialogues to improve my pronunciation. Recording myself speaking and comparing it to native speakers helps me identify areas that need improvement."}]}'),

-- INTERMEDIATE conversations
-- INTERMEDIATE conversations (10 scenarios - open ended but easier topics)

('Education Systems', 'conversation', 'INTERMEDIATE', 'Discuss different education approaches and learning methods - IELTS Part 2/3 topic',
 '{"id": "education-systems", "name": "Education Systems", "level": "INTERMEDIATE", "description": "Discuss different education approaches and learning methods - IELTS Part 2/3 topic", "greeting": "Let''s discuss education. How would you compare the education system in your country with other countries you know about?", "instructions": "You are an IELTS examiner conducting Part 2/3 discussion about education. Encourage analytical thinking and comparison of different educational approaches.", "turns": 6, "icon": "🎓"}'),

('Work-Life Balance', 'conversation', 'INTERMEDIATE', 'Explore modern workplace challenges and lifestyle choices - IELTS Part 2/3 topic',
 '{"id": "work-life-balance", "name": "Work-Life Balance", "level": "INTERMEDIATE", "description": "Explore modern workplace challenges and lifestyle choices - IELTS Part 2/3 topic", "greeting": "Many people today struggle with balancing work and personal life. What do you think are the main challenges people face in achieving work-life balance?", "instructions": "You are an IELTS examiner discussing work-life balance. Guide the conversation toward causes, effects, and solutions.", "turns": 6, "icon": "⚖️"}'),

('Cultural Traditions', 'conversation', 'INTERMEDIATE', 'Analyze the importance of cultural heritage in modern society - IELTS Part 2/3 topic',
 '{"id": "cultural-traditions", "name": "Cultural Traditions", "level": "INTERMEDIATE", "description": "Analyze the importance of cultural heritage in modern society - IELTS Part 2/3 topic", "greeting": "Let''s talk about cultural traditions. How important do you think it is for young people to maintain traditional customs and practices?", "instructions": "You are an IELTS examiner exploring cultural preservation. Encourage discussion about tradition vs. modernization and generational differences.", "turns": 6, "icon": "🏮"}'),

('Urban Development', 'conversation', 'INTERMEDIATE', 'Examine city planning and urbanization effects - IELTS Part 2/3 topic',
 '{"id": "urban-development", "name": "Urban Development", "level": "INTERMEDIATE", "description": "Examine city planning and urbanization effects - IELTS Part 2/3 topic", "greeting": "Cities are growing rapidly around the world. What do you think are the main advantages and disadvantages of urban development?", "instructions": "You are an IELTS examiner discussing urbanization. Focus on comparing city vs. rural life, infrastructure challenges, and future planning.", "turns": 6, "icon": "🏙️"}'),

('Media and Information', 'conversation', 'INTERMEDIATE', 'Discuss media influence and information reliability - IELTS Part 2/3 topic',
 '{"id": "media-information", "name": "Media and Information", "level": "INTERMEDIATE", "description": "Discuss media influence and information reliability - IELTS Part 2/3 topic", "greeting": "In today''s digital age, we receive information from many different sources. How do you think people can distinguish between reliable and unreliable information?", "instructions": "You are an IELTS examiner exploring media literacy. Guide discussion toward information sources, social media impact, and critical thinking.", "turns": 6, "icon": "📱"}'),

('Healthcare Systems', 'conversation', 'INTERMEDIATE', 'Compare different approaches to healthcare and wellness - IELTS Part 2/3 topic',
 '{"id": "healthcare-systems", "name": "Healthcare Systems", "level": "INTERMEDIATE", "description": "Compare different approaches to healthcare and wellness - IELTS Part 2/3 topic", "greeting": "Healthcare is organized differently in various countries. What do you think makes a healthcare system effective?", "instructions": "You are an IELTS examiner discussing healthcare. Encourage comparison of public vs. private systems, prevention vs. treatment, and accessibility issues.", "turns": 6, "icon": "🏥"}'),

('Consumer Culture', 'conversation', 'INTERMEDIATE', 'Analyze shopping habits and consumer behavior - IELTS Part 2/3 topic',
 '{"id": "consumer-culture", "name": "Consumer Culture", "level": "INTERMEDIATE", "description": "Analyze shopping habits and consumer behavior - IELTS Part 2/3 topic", "greeting": "Modern society is often described as consumer-oriented. Do you think people today buy more than they actually need?", "instructions": "You are an IELTS examiner exploring consumer behavior. Focus on advertising influence, materialism, and sustainable consumption.", "turns": 6, "icon": "🛍️"}'),

('Generation Gap', 'conversation', 'INTERMEDIATE', 'Explore differences between generations and their causes - IELTS Part 2/3 topic',
 '{"id": "generation-gap", "name": "Generation Gap", "level": "INTERMEDIATE", "description": "Explore differences between generations and their causes - IELTS Part 2/3 topic", "greeting": "There are often differences in attitudes and values between older and younger generations. What do you think causes these generational differences?", "instructions": "You are an IELTS examiner discussing generational differences. Guide conversation toward technology impact, changing values, and family relationships.", "turns": 6, "icon": "👴👶"}'),

('Tourism Impact', 'conversation', 'INTERMEDIATE', 'Examine tourism effects on local communities and environments - IELTS Part 2/3 topic',
 '{"id": "tourism-impact", "name": "Tourism Impact", "level": "INTERMEDIATE", "description": "Examine tourism effects on local communities and environments - IELTS Part 2/3 topic", "greeting": "Tourism brings both benefits and challenges to destinations. How do you think tourism affects local communities?", "instructions": "You are an IELTS examiner exploring tourism impacts. Discuss economic benefits, cultural effects, environmental concerns, and sustainable tourism.", "turns": 6, "icon": "🗺️"}'),

('Social Media Society', 'conversation', 'INTERMEDIATE', 'Analyze social media''s role in modern communication and relationships - IELTS Part 2/3 topic',
 '{"id": "social-media-society", "name": "Social Media Society", "level": "INTERMEDIATE", "description": "Analyze social media''s role in modern communication and relationships - IELTS Part 2/3 topic", "greeting": "Social media has changed how people communicate and form relationships. Do you think these changes are mostly positive or negative?", "instructions": "You are an IELTS examiner discussing social media impact. Focus on communication changes, relationship quality, privacy concerns, and social comparison.", "turns": 6, "icon": "📲"}'),

-- ADVANCED conversations (10 scenarios - harder, complex topics)

('Artificial Intelligence Ethics', 'conversation', 'ADVANCED', 'Debate the ethical implications of AI development and implementation',
 '{"id": "ai-ethics", "name": "Artificial Intelligence Ethics", "level": "ADVANCED", "description": "Debate the ethical implications of AI development and implementation", "greeting": "Artificial intelligence is rapidly advancing and affecting many aspects of society. What ethical considerations should guide AI development?", "instructions": "You are an IELTS examiner exploring complex AI ethics. Encourage sophisticated discussion about automation, privacy, decision-making algorithms, and human-AI relationships.", "turns": 8, "icon": "🤖"}'),

('Global Economic Inequality', 'conversation', 'ADVANCED', 'Analyze causes and solutions for worldwide economic disparities',
 '{"id": "global-economic-inequality", "name": "Global Economic Inequality", "level": "ADVANCED", "description": "Analyze causes and solutions for worldwide economic disparities", "greeting": "Economic inequality exists both within and between countries. What do you believe are the root causes of global economic inequality?", "instructions": "You are an IELTS examiner discussing complex economic issues. Guide toward historical factors, globalization effects, policy solutions, and sustainable development.", "turns": 8, "icon": "💰"}'),

('Climate Change Governance', 'conversation', 'ADVANCED', 'Examine international cooperation and policy responses to climate change',
 '{"id": "climate-change-governance", "name": "Climate Change Governance", "level": "ADVANCED", "description": "Examine international cooperation and policy responses to climate change", "greeting": "Climate change requires coordinated global action, yet countries often have conflicting interests. How can the international community effectively address climate change?", "instructions": "You are an IELTS examiner exploring climate governance. Discuss international agreements, national interests, economic trade-offs, and enforcement mechanisms.", "turns": 8, "icon": "🌍"}'),

('Biotechnology and Society', 'conversation', 'ADVANCED', 'Explore the societal implications of genetic engineering and biotechnology',
 '{"id": "biotechnology-society", "name": "Biotechnology and Society", "level": "ADVANCED", "description": "Explore the societal implications of genetic engineering and biotechnology", "greeting": "Advances in biotechnology, including genetic engineering, are creating new possibilities and dilemmas. How should society approach the regulation and application of these technologies?", "instructions": "You are an IELTS examiner discussing biotechnology ethics. Encourage analysis of genetic modification, medical applications, environmental impacts, and regulatory frameworks.", "turns": 8, "icon": "🧬"}'),

('Democracy and Digital Age', 'conversation', 'ADVANCED', 'Analyze how digital technology affects democratic processes and civic engagement',
 '{"id": "democracy-digital-age", "name": "Democracy and Digital Age", "level": "ADVANCED", "description": "Analyze how digital technology affects democratic processes and civic engagement", "greeting": "Digital technology is transforming how democratic societies function. What are the implications of digitalization for democratic participation and governance?", "instructions": "You are an IELTS examiner exploring digital democracy. Discuss online voting, information manipulation, digital divide, transparency, and citizen engagement.", "turns": 8, "icon": "🗳️"}'),

('Cultural Globalization', 'conversation', 'ADVANCED', 'Examine the spread of global culture and its impact on local identities',
 '{"id": "cultural-globalization", "name": "Cultural Globalization", "level": "ADVANCED", "description": "Examine the spread of global culture and its impact on local identities", "greeting": "Globalization has led to the worldwide spread of certain cultural practices and values. How does this cultural homogenization affect local cultures and identities?", "instructions": "You are an IELTS examiner discussing cultural globalization. Explore cultural imperialism, identity preservation, hybridization, and the role of media and technology.", "turns": 8, "icon": "🌐"}'),

('Space Exploration Ethics', 'conversation', 'ADVANCED', 'Debate the priorities and ethics of space exploration and colonization',
 '{"id": "space-exploration-ethics", "name": "Space Exploration Ethics", "level": "ADVANCED", "description": "Debate the priorities and ethics of space exploration and colonization", "greeting": "As space exploration advances toward potential colonization of other planets, various ethical questions arise. Should humanity prioritize space exploration or focus resources on Earth''s problems?", "instructions": "You are an IELTS examiner exploring space ethics. Discuss resource allocation, planetary protection, space governance, and the implications of becoming a multiplanetary species.", "turns": 8, "icon": "🚀"}'),

('Future of Human Enhancement', 'conversation', 'ADVANCED', 'Explore the implications of human augmentation technologies',
 '{"id": "future-human-enhancement", "name": "Future of Human Enhancement", "level": "ADVANCED", "description": "Explore the implications of human augmentation technologies", "greeting": "Technologies for enhancing human physical and cognitive abilities are becoming increasingly sophisticated. What are the potential benefits and risks of human enhancement?", "instructions": "You are an IELTS examiner discussing human enhancement. Explore cognitive enhancement, life extension, inequality concerns, human nature, and regulatory challenges.", "turns": 8, "icon": "🧠"}'),

('Post-Truth Society', 'conversation', 'ADVANCED', 'Analyze the challenges of truth and knowledge in the information age',
 '{"id": "post-truth-society", "name": "Post-Truth Society", "level": "ADVANCED", "description": "Analyze the challenges of truth and knowledge in the information age", "greeting": "We often hear about living in a ''post-truth'' era where objective facts seem less influential than personal beliefs. What factors have contributed to this phenomenon?", "instructions": "You are an IELTS examiner exploring post-truth dynamics. Discuss epistemic challenges, filter bubbles, institutional trust, scientific literacy, and the nature of knowledge.", "turns": 8, "icon": "❓"}'),

('Automation and Future Work', 'conversation', 'ADVANCED', 'Examine how automation will reshape employment and society',
 '{"id": "automation-future-work", "name": "Automation and Future Work", "level": "ADVANCED", "description": "Examine how automation will reshape employment and society", "greeting": "Automation and AI are expected to significantly change the nature of work in the coming decades. How should society prepare for and manage this transformation?", "instructions": "You are an IELTS examiner discussing automation''s impact on work. Explore job displacement, reskilling, universal basic income, human-AI collaboration, and economic restructuring.", "turns": 8, "icon": "🏭"}');

-- Insert pronunciation assignments
insert into public.practice_assignments (title, type, level, description, content) values
-- BEGINNER pronunciation
('Basic Personal Information', 'pronunciation', 'BEGINNER', 'Practice saying your name, age, and where you are from', 
 '{"transcript": "My name is Sarah Johnson. I am twenty-five years old. I am from Toronto, Canada."}'),

('Daily Routine', 'pronunciation', 'BEGINNER', 'Describe simple daily activities with clear pronunciation',
 '{"transcript": "I wake up at seven o''clock every morning. I brush my teeth and eat breakfast."}'),

('Family Members', 'pronunciation', 'BEGINNER', 'Practice family vocabulary and relationships',
 '{"transcript": "I have two brothers and one sister. My parents live in the same city as me."}'),

('Food and Drinks', 'pronunciation', 'BEGINNER', 'Practice food vocabulary and preferences',
 '{"transcript": "I like pizza and chocolate ice cream. My favorite drink is orange juice."}'),

('Weather Descriptions', 'pronunciation', 'BEGINNER', 'Describe weather conditions clearly',
 '{"transcript": "Today is sunny and warm. Yesterday it was cloudy and a little bit cold."}'),

('Shopping Items', 'pronunciation', 'BEGINNER', 'Practice shopping vocabulary and quantities',
 '{"transcript": "I need to buy three apples, two bottles of milk, and one loaf of bread."}'),

('Time and Dates', 'pronunciation', 'BEGINNER', 'Practice saying times, days, and dates',
 '{"transcript": "The meeting is on Monday at three thirty in the afternoon."}'),

('Transportation', 'pronunciation', 'BEGINNER', 'Practice transportation vocabulary',
 '{"transcript": "I go to work by bus every day. Sometimes I walk when the weather is nice."}'),

-- INTERMEDIATE pronunciation
('Work Experience', 'pronunciation', 'INTERMEDIATE', 'Describe professional background and responsibilities',
 '{"transcript": "I have been working as a marketing coordinator for three years. My responsibilities include managing social media campaigns and analyzing customer feedback."}'),

('Travel Experiences', 'pronunciation', 'INTERMEDIATE', 'Share detailed travel stories and cultural observations',
 '{"transcript": "Last summer, I traveled to Japan for two weeks. The most interesting experience was visiting traditional temples in Kyoto and learning about Japanese tea ceremony."}'),

('Educational Background', 'pronunciation', 'INTERMEDIATE', 'Discuss academic achievements and learning experiences',
 '{"transcript": "I graduated from university with a degree in computer science. During my studies, I specialized in artificial intelligence and completed several challenging projects."}'),

('Future Plans and Goals', 'pronunciation', 'INTERMEDIATE', 'Express aspirations and long-term objectives',
 '{"transcript": "In the next five years, I plan to start my own technology company. I believe innovation in renewable energy will create significant opportunities for entrepreneurs."}'),

('Cultural Differences', 'pronunciation', 'INTERMEDIATE', 'Compare and contrast cultural practices and values',
 '{"transcript": "There are notable differences between Eastern and Western approaches to work-life balance. While Western cultures often emphasize individual achievement, Eastern cultures prioritize collective harmony."}'),

('Environmental Issues', 'pronunciation', 'INTERMEDIATE', 'Discuss environmental challenges and solutions',
 '{"transcript": "Climate change is one of the most pressing issues of our time. Governments and individuals must collaborate to implement sustainable practices and reduce carbon emissions."}'),

-- ADVANCED pronunciation
('Philosophical Perspectives', 'pronunciation', 'ADVANCED', 'Express complex philosophical ideas and arguments',
 '{"transcript": "The relationship between free will and determinism has been debated by philosophers for centuries. While some argue that our choices are predetermined by causal factors, others maintain that humans possess genuine autonomy in their decision-making processes."}'),

('Economic Analysis', 'pronunciation', 'ADVANCED', 'Discuss complex economic theories and market dynamics',
 '{"transcript": "The implementation of quantitative easing policies during economic recessions demonstrates the central bank''s commitment to maintaining liquidity in financial markets, although critics argue that such measures may contribute to asset price inflation and increase wealth inequality."}'),

('Scientific Research', 'pronunciation', 'ADVANCED', 'Explain research methodologies and scientific discoveries',
 '{"transcript": "Recent advances in CRISPR gene editing technology have revolutionized our understanding of genetic modification. However, the ethical implications of human genetic enhancement raise fundamental questions about the future of human evolution and the potential for creating genetic inequalities."}'),

('Political Commentary', 'pronunciation', 'ADVANCED', 'Analyze political systems and policy implications',
 '{"transcript": "The effectiveness of democratic institutions depends largely on the active participation of informed citizens. However, the proliferation of misinformation through social media platforms poses significant challenges to the democratic process and requires comprehensive regulatory frameworks."}'),

('Literary Analysis', 'pronunciation', 'ADVANCED', 'Discuss literature and artistic interpretation',
 '{"transcript": "Shakespeare''s exploration of human ambition in Macbeth reveals the psychological transformation that occurs when moral boundaries are transgressed. The protagonist''s descent into tyranny illustrates the corrupting influence of unchecked power and the inevitable consequences of betraying one''s ethical principles."}'),

('Technological Ethics', 'pronunciation', 'ADVANCED', 'Examine ethical implications of technological advancement',
 '{"transcript": "The development of artificial intelligence systems capable of autonomous decision-making raises profound questions about responsibility and accountability. As machines become increasingly sophisticated, society must establish comprehensive ethical frameworks to govern their deployment and ensure human oversight remains paramount."}');

-- Create indexes
create index if not exists idx_practice_assignments_type_level on public.practice_assignments(type, level);
create index if not exists idx_curriculum_assignments_curriculum_week on public.curriculum_assignments(curriculum_id, week_number);
